services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: spotyvoice
      POSTGRES_USER: spotyvoice
      POSTGRES_PASSWORD: spotyvoice
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
