const ERROR_CODES = {
    BAD_REQUEST: "BAD_REQUEST",
    CONFLICT: "CONFLICT",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    NOT_FOUND: "NOT FOUND",
    UNAUTHORIZED: "UNAUTHORIZED",
    VALIDATION_ERROR: "VALIDATION_ERROR",

    POLL_ALREADY_VOTED: "POLL_ALREADY_VOTED",

    SPOTIFY_HTTP_ERROR: "SPOTIFY_HTTP_ERROR",
};

export default ERROR_CODES;
